swagger: "2.0"
info:
  version: 0.0.2
  title: ServU

# during dev, should point to your local machine
host: 127.0.0.1:3000

# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/x-www-form-urlencoded
  - test/html
  - text/plain
  #ajouter xml si on a le temps
# format of the responses to the client (Accepts)
produces:
  - application/json
  - application/x-www-form-urlencoded
  - text/html
  - text/plain
  #idem xml


parameters:
  username:
    name: username
    description: "Name of the user"
    in: path
    type: string
    required: true

  uuid:
    name: uuid
    description: "uuid of the device"
    in: path
    type: string
    required: true

  action:
    name: action
    description: "Action object"
    in: body
    required: true
    schema:
      $ref: "#/definitions/actionUser_post"

  login:
    name: login
    description: "login object"
    in: body
    required: true
    schema:
      $ref: "#/definitions/login"





paths:
# ######################
#     API USER SIDE
# ######################


  /users:
    x-swagger-router-controller: users

    post:
      operationId: postUsers
      description: Add a new user
      parameters:
        - name: user
          in: body
          description: User's informations
          required: true
          schema:
            $ref: "#/definitions/user_post"
      responses:
        "201":
          description: Success
        "400":
          description: Wrong format
        "409":
          description: Another user has the same username

  /users/{username}:
    x-swagger-router-controller: users
    get:
      operationId: getUsersUsername
      description: Returns a user
      parameters:
      - $ref: "#/parameters/username"
      responses:
        "201":
          description: Success
          schema:
            $ref: "#/definitions/user"
        "404":
          description: User not found
    put:
      operationId: putUsersUsername
      description: Update a user
      parameters:
        - $ref: "#/parameters/username"
        - name: user
          in: body
          description: User's informations
          required: true
          schema:
              $ref: "#/definitions/user_put"
      responses:
        "204":
          description: Success
        "400":
          description: Wrong format
        "404":
          description: User not found
        "409":
          description: Another user has the same pseudo
    delete:
      operationId: deleteUsersUsername
      description: Delete a user
      parameters:
        - $ref: "#/parameters/username"
      responses:
        "204":
          description: Success
        "404":
          description: User not found

  /users/login:
    x-swagger-router-controller: users
    post:
      operationId: postLogin
      description: Vérification du login
      parameters:
        - $ref: "#/parameters/login"
      responses:
        "201":
          description: Success
        "404":
          description: User not found

  /users/{username}/devices:
    x-swagger-router-controller: users
    get:
      operationId: getUsersDevice
      description: Returns all devices attached to the user
      parameters:
        - $ref: "#/parameters/username"
      responses:
        "200":
          description: "Success"
          schema:
            type: object
            items:
              $ref: "#/definitions/device"
        "404":
          description: "This user does not exist or has no devices"
    post:
      operationId: postUsersDevice
      description: "Add a device"
      parameters:
      - $ref: "#/parameters/username"
      - name: device
        description: "Device to add"
        in: body
        schema:
          $ref: "#/definitions/device"
        required: true
      responses:
        "201":
          description: Success
          schema:
            $ref: "#/definitions/device"
        "400":
          description: Wrong format
        "404":
          description: User not found

  /users/{username}/devices/{uuid}:
    x-swagger-router-controller: users
    get:
      operationId: getUsersDeviceUuid
      description: Returns informations about the device
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/device"
        "404":
          description: User or device not found
    delete:
      operationId: deleteUsersDeviceUuid
      description: Delete a device
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
      responses:
        "204":
          description: Success
        "404":
          description: User or device not found

  /users/{username}/devices/{uuid}/probes:
    x-swagger-router-controller: users
    get:
      operationId: getUsersDeviceUuidProbes
      description: Get the list of probes for this device
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/probe"
        "404":
          description: User or device not found

  /users/{username}/devices/{uuid}/probes/{name}:
    x-swagger-router-controller: users
    get:
      operationId: getUsersDeviceUuidProbesName
      description: Get the informations of the probe for this device
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
        - name: name
          description: Name of the probe wanted
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/probe"
        "404":
          description: Probe not found

  /users/{username}/devices/{uuid}/actions:
    x-swagger-router-controller: users
    get:

      description: Get the list of actions availables for this device
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/action"
        "404":
          description: User or device not found
    post:
      operationId: postUsersDeviceUuidActions
      description: Trigger an action for this device
      parameters:
      - $ref: "#/parameters/username"
      - $ref: "#/parameters/uuid"
      - $ref: "#/parameters/action"
      responses:
        "201":
          description: Action added
        "400":
          description: Wrong format
        "404":
          description: User or device not found

  /users/{username}/devices/{uuid}/actions/{action_id}:
    x-swagger-router-controller: users
    get:
      operationId: bbbb
      description: Get the informations about this action
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
        - name: action_id
          description: Id of the action
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/action"
        "404":
          description: Action not found
    delete:
      operationId: deleteUsersDeviceUuidActions
      description: Delete this action
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
        - name: action_id
          description: Id of the action
          in: path
          type: string
          required: true
      responses:
        "204":
          description: Success
        "404":
          description: Action not found



# ####################
#    API PHONE SIDE
# ####################

  /phone:
    x-swagger-router-controller: phone
    post:
      operationId: postPhone
      description: "Create the 1st time the phone"
      parameters:
        - name: uuid
          description: "uuid of the device"
          in: body
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Success
        "400":
          description: Wrong format
        "409":
          description: Conflict on post

  /phone/{uuid}/probes:
    x-swagger-router-controller: phone
    post:
      operationId: postProbes
      description: "Create the 1st time the probes avalailables for this phone"
      parameters:
        - $ref: "#/parameters/uuid"
        - name: probes
          description: "array containing the probes availables and the status of this probes"
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/probe"
      responses:
        "201":
          description: Success
        "400":
          description: Wrong format
        "404":
          description: uuid not found
        "409":
          description: Conflict on post
    put:
      operationId: putProbes
      description: "Update the status of the probes"
      parameters:
        - $ref: "#/parameters/uuid"
        - name: probes
          description: "array containing the status"
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/probe"
      responses:
        "204":
          description: "Success"
        "400":
          description: "Wrong format"
        "404":
          description: "uuid not found"

  /phone/{uuid}/actions:
    x-swagger-router-controller: phone

    post:
      operationId: postActions
      description: "Post the actions availables on this phone (chose by user)"
      parameters:
        - $ref: "#/parameters/uuid"
        - name: actions
          description: "object of actions available on this phone"
          required: true
          in: body
          schema:
            type: array
            items:
              $ref: "#/definitions/action_post"
      responses:
        "201":
          description: "Success"
        "400":
          description: "Wrong format"
        "404":
          description: "Device or action id not found"
        "409":
          description: "Conflict"
    get:
      operationId: getActions
      description: "Get the action in top queue to do"
      parameters:
        - $ref: "#/parameters/uuid"
      responses:
        "200":
          description: "Return the action to do"
          schema:
            type: object


        "404":
          description: "Device not found or no action"
    put:
      operationId: putActions
      description: "Update the actions availables on this phone (chose by user)"
      parameters:
        - $ref: "#/parameters/uuid"
        - name: actions
          description: "Array of actions available on this phone"
          required: true
          in: body
          schema:
            type: array
            items:
              $ref: "#/definitions/action_post"
      responses:
        "201":
          description: "Success"
        "400":
          description: "Wrong format"
        "404":
          description: "Device or action id not found"




  /phone/{uuid}/actions_user:
    x-swagger-router-controller: phone

    get:
      operationId: getActionsUser
      description: "Get the action in top queue to do"
      parameters:
        - $ref: "#/parameters/uuid"
      responses:
        "200":
          description: "Return the action to do"
          schema:
            type: array
            items:
              $ref: "#/definitions/action"
        "404":
          description: "Device not found"
    put:
      operationId: putActionsUser
      description: "Update the user action"
      parameters:
        - $ref: "#/parameters/uuid"
        - name: ActionStatus
          description: "Status of the action"
          required: true
          in: body
          schema:
            type: array
            items:
              $ref: "#/definitions/action_put"
      responses:
        "201":
          description: "Success"
        "400":
          description: "Wrong format"
        "404":
          description: "Device or action id not found"


# complex objects have schema definitions

definitions:

  login:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
        format: password


  user:
    type: object

    properties:
      username:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      devices:
        type: object

  user_post:
    type: object
    required:
      - username
      - firstname
      - lastname
      - email
      - password
    properties:
      username:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      password:
        type: string
        format: password
      devices:
        type: object


  user_put:
    type: object

    properties:
      username:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      password:
        type: string
        format: password
      devices:
        type: object



  device:
    type: object
    required:
      - name
      - platform
      - uuid
    properties:
      name:
        type: string
      manufacturer:
        type: string
      model:
        type: string
      platform:
        type: string
      version:
        type: string
      serial:
        type: string
      uuid:
        type: string

  probe:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      active:
        type: boolean
      data:
        type: string

  action:
    type: object
    required:
      - name
    properties:
      id:
        type: string
      name:
        type: string
      status:
        $ref: "#/definitions/status"
      data:
        type: object
      creation_date:
        type: string
      parameters:
        type: object

  actionUser_post:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      status:
        $ref: "#/definitions/status"
      data:
        type: object
      creation_date:
        type: string



  action_put:
    type: object
    properties:
      actionId:
        type: integer
      status:
        $ref: "#/definitions/status"

  status:
    type: string
    enum: ["pending","in progress","done"]

  action_post:
    type: object
    properties:
      name:
        type: string
      active:
        type: boolean
