swagger: "2.0"
info:
  version: 0.0.2
  title: ServU
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  #ajouter xml si on a le temps
# format of the responses to the client (Accepts)
produces:
  - application/json
  #idem xml




parameters:
  username:
    name: username
    description: "Name of the user"
    in: path
    type: string
    required: true

  uuid:
    name: uuid
    description: "uuid of the device"
    in: path
    type: string
    required: true

  action:
    name: action
    description: "Action object"
    in: body
    required: true
    schema:
      $ref: "#/definitions/action_post"






paths:
# ######################
#     API USER SIDE
# ######################

  /users:
    get:
      description: Returns all the users
      parameters:
        - name: firstname
          in: query
          required: false
          type: string
        - name: lastname
          in: query
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/user"
        "404":
          description: User not found
    post:
      description: Add a new user
      parameters:
        - name: user
          in: body
          description: User's informations
          required: true
          schema:
            $ref: "#/definitions/user_post"
      responses:
        "201":
          description: Success
        "400":
          description: Wrong format
        "409":
          description: Another user has the same username

  /users/{username}:
    get:
      description: Returns a user
      parameters:
      - $ref: "#/parameters/username"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/user"
        "404":
          description: User not found
    put:
      description: Update a user
      parameters:
        - $ref: "#/parameters/username"
        - name: user
          in: body
          description: User's informations
          required: true
          schema:
              $ref: "#/definitions/user_post"
      responses:
        "204":
          description: Success
        "400":
          description: Wrong format
        "404":
          description: User not found
        "409":
          description: Another user has the same pseudo
    delete:
      description: Delete a user
      parameters:
        - $ref: "#/parameters/username"
      responses:
        "204":
          description: Success
        "404":
          description: User not found

  /users/{username}/devices:
    get:
      description: Returns all devices attached to the user
      parameters:
        - $ref: "#/parameters/username"
      responses:
        "200":
          description: "Success"
          schema:
            type: array
            items:
              $ref: "#/definitions/device"
        "404":
          description: "This user does not exist or has no devices"
    post:
      description: "Add a device"
      parameters:
      - $ref: "#/parameters/username"
      - name: device
        description: "Device to add"
        in: body
        schema:
          $ref: "#/definitions/device"
        required: true
      responses:
        "201":
          description: Success
          schema:
            $ref: "#/definitions/device"
        "400":
          description: Wrong format
        "404":
          description: User not found

  /users/{username}/devices/{uuid}:
    get:
      description: Returns informations about the device
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/device"
        "404":
          description: User or device not found
    delete:
      description: Delete a device
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
      responses:
        "204":
          description: Success
        "404":
          description: User or device not found

  /users/{username}/devices/{uuid}/probes:
    get:
      description: Get the list of probes for this device
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/probe"
        "404":
          description: User or device not found

  /users/{username}/devices/{uuid}/probes/{name}:
    get:
      description: Get the informations of the probe for this device
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
        - name: name
          description: Name of the probe wanted
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/probe"
        "404":
          description: Probe not found

  /users/{username}/devices/{uuid}/actions:
    get:
      description: Get the list of actions availables for this device
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/action"
        "404":
          description: User or device not found
    post:
      description: Trigger an action for this device
      parameters:
      - $ref: "#/parameters/username"
      - $ref: "#/parameters/uuid"
      - $ref: "#/parameters/action"
      responses:
        "201":
          description: Action added
        "400":
          description: Wrong format
        "404":
          description: User or device not found

  /users/{username}/devices/{uuid}/actions/{action-id}:
    get:
      description: Get the informations about this action
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
        - name: action-id
          description: Id of the action
          in: path
          type: string
          required: true
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/action"
        "404":
          description: Action not found
    delete:
      description: Delete this action
      parameters:
        - $ref: "#/parameters/username"
        - $ref: "#/parameters/uuid"
        - name: action-id
          description: Id of the action
          in: path
          type: string
          required: true
      responses:
        "204":
          description: Success
        "404":
          description: Action not found



# ####################
#    API PHONE SIDE
# ####################

  /phone/{uuid}/probes:
    x-swagger-router-controller: phone
    post:
      operationId: postProbes
      description: "Create the 1st time the probes avalailables for this phone"
      parameters:
        - $ref: "#/parameters/uuid"
        - name: probes
          description: "array containing the probes availables and the status of this probes"
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/probe"
      responses:
        "201":
          description: Success
        "404":
          description: uuid not found
    put:
      operationId: putProbes
      description: "Update the status of the probes"
      parameters:
        - $ref: "#/parameters/uuid"
        - name: probes
          description: "array containing the status"
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/probe"
      responses:
        "204":
          description: "Success"
        "400":
          description: "Wrong format"
        "404":
          description: "uuid not found"

  /phone/{uuid}/actions:
    post:
      description: "Post the actions availables on this phone"
      parameters:
        - $ref: "#/parameters/uuid"
        - name: actions
          description: "Array of actions available on this phone"
          required: true
          in: body
          schema:
            type: array
            items:
              $ref: "#/definitions/action_post"
      responses:
        "201":
          description: "Success"
        "400":
          description: "Wrong format"
        "404":
          description: "Device or action id not found"

  /phone/{uuid}/action:
    get:
      description: "Get the action in top queue to do"
      parameters:
        - $ref: "#/parameters/uuid"
      responses:
        "200":
          description: "Return the action to do"
          schema:
            $ref: "#/definitions/action"
        "404":
          description: "Device not found"

  /phone/{uuid}/action/{action-id}:
    put:
      description: "Update the action for that id needed. Ex update action status"
      parameters:
        - $ref: "#/parameters/uuid"
        - name: action-id
          description: id de l'actiona mettre a jour
          type: string
          required: true
          in: path
        - name: status
          description: status of this action
          type: string
          enum: ["pending","in progress","done"]
          required: true
          in: query
      responses:
        "204":
          description: "Success"
        "404":
          description: "Device not found"


# complex objects have schema definitions

definitions:
  user:
    type: object
    required:
      - username
      - firstname
      - lastname
      - email
    properties:
      username:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string

  user_post:
    type: object
    required:
      - username
      - firstname
      - lastname
      - email
      - password
    properties:
      username:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      password:
        type: string
        format: password

  device:
    type: object
    required:
      - name
      - platform
      - uuid
    properties:
      name:
        type: string
      manufacturer:
        type: string
      model:
        type: string
      platform:
        type: string
      version:
        type: string
      serial:
        type: string
      uuid:
        type: string

  probe:
    type: object
    required:
      - name
      - active
    properties:
      name:
        type: string
      active:
        type: boolean
      data:
        type: string

  action:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
      name:
        type: string
      status:
        $ref: "#/definitions/status"

      creation-date:
        type: string
        format: date
      parameters:
        type: object

  status:
    type: string
    enum: ["pending","in progress","done"]

  action_post:
    type: object
    properties:
      name:
        type: string
